### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by muzhaohui** [Ze-Yang/Lane-Detection-with-ERFNet#3]
想问一下您清洗后得数据集能发一下吗？百度网盘或者谷歌Drive都行。或者有没有清洗数据集的py代码呢？如果是人工找的，那可太励志了！

**Comment by Ze-Yang** [comment]
You can download it [here](https://drive.google.com/file/d/1X-ej4QQXf6UgpIz13nSpl__r3FjhvUx2/view?usp=sharing).

**Comment by muzhaohui** [comment]
Thank you!
