### ISSUE TITLE
black

### ISSUE THREAD

**Issue by legendary111** [Ze-Yang/Lane-Detection-with-ERFNet#5]
你好，我有一个问题，我是在windows下，按照您所说的环境正确配置，然后利用给出的权重文件进行预测，中途不报错，但是最终预测的结果图片全黑，不清楚哪里的问题

**Comment by Ze-Yang** [comment]
因为预测结果的像素值在0-19，所以看上去就是基本全黑的，你需要做伪彩色或者把数值乘10再可视化。

**Comment by legendary111** [comment]
谢谢！
