### ISSUE TITLE
保存为推理模式

### ISSUE THREAD

**Issue by legendary111** [Ze-Yang/Lane-Detection-with-ERFNet#6]
我看您的保存模式文件为.pdopt和.pdparams
但是本人要做部署，需要转为onnx模式
怎么使用save_inference_model接口保存为推理模式
好像还需要动态图先转为静态图，才可以后续的保存推理模式
如今卡在这一步，对paddle不是很熟悉，如果您有时间，烦请赐教一下

**Comment by Ze-Yang** [comment]
抱歉，我对paddle框架也不太了解，你可能需要查阅相关资料来解决。

**Comment by legendary111** [comment]
thank you!
